### ISSUE TITLE
Links in SPAs

### ISSUE THREAD

**Issue by amkoehler** [afry/quill-mention#84]
We're making use of the `link` attribute to render our mentions as links. This works great, but I was wondering if there was a more SPA-friendly way to handle links. Right now clicking a link will do a full page refresh to load that page and we'd like to hook into our routing library to handle the navigation in a way that's consistent with the rest of our app. I imagine the psuedocode would be something like this:

```
onLinkClick: (e) => {
  e.preventDefault(); // Prevent default execution for `<a>` tags

  router.navigate(...); // Use routing library to navigate
}
```

I completely understand if supporting this type of thing isn't on your radar.

**Comment by edowney29** [comment]
This worked for me well. By using a unique id and after Quill is initialized, go through each `mention` class and add a click event emitter. I added the custom attribute with `dataAttributes` in the mention properties of Quill which was a JSON string containing user data.

``` ts
    const editor = new Quill(document.getElementById(this.id), {})

    Array.prototype.forEach.call(
      document.getElementById(this.id).getElementsByClassName("mention"),
      (element: Element) => {
        const data = JSON.parse(element.getAttribute("data-out"));
        element.addEventListener(
          "click",
          () => this.onMentionClick.emit(data),
          true
        );
      }
    );
```

**Comment by guille-alibrate** [comment]
Do you guys have to deal with native too? I mean, how would you handle the links in, say, react native? I'm scratching my head thinking about how the generated html could be useful for both web and mobile. 

I wish I could store something like `[@mention:id]` instead of a span. That would be easier to parse. And that's quite common in non-rich text editors. Like:

https://medium.com/@mrazadar/react-native-mentions-component-7aaa44cab109
https://github.com/taskrabbit/react-native-parsed-text

**Comment by guille-alibrate** [comment]
Solved it using https://github.com/archriss/react-native-render-html . It has a `onLinkPress` method. So, you can do something like:

```
const onMentionPress = useCallback((e, link) => {
    const userId = link.split('/').pop()
    // TODO: navigate
    })
  }, [])
```
